[Improvement] added more install options to the README.md
prettier/eslint-config-prettier pull request #284
Opened 2024-04-04 13:12 UTC by AngelDarco

I just added the options to install with yarn, pnpm and bun

2024-04-07 12:49 UTC, the-homeless-god requested changes

2024-04-07 12:49 UTC, the-homeless-god commented on README.md
> +   npm i -D eslint-config-prettier
Change it please to `shell`

```suggestion
   ``` shell
   npm i -D eslint-config-prettier
```

2024-04-07 12:49 UTC, the-homeless-god commented on README.md
> +   bun add -D eslint-config-prettier
Change it please to `shell` instead `javascript`

2024-04-12 16:10 UTC, AngelDarco reviewed
I apologize for the mistake in my previous post. I already updated it. Thank you for bringing it to my attention.

2024-04-14 21:03 UTC, closed without merging